<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.w3.org/1999/xhtml"
                xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                xmlns:map="http://www.w3.org/2005/xpath-functions/map"
                xmlns:tei="http://www.tei-c.org/ns/1.0"
                xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="#all"
                xpath-default-namespace="http://www.w3.org/1999/xhtml"
                version="3.0">
   <xd:doc scope="stylesheet">
      <xd:desc>
         <xd:p>Created on 2026-03-29 by an automated process.</xd:p>
         <xd:p>
            <xd:b>Authors:</xd:b> Joey Takeda and Martin Holmes</xd:p>
         <xd:p>This is the temporary stylesheet derived from file:///Users/takeda/projects/wilde/static/staticSearch_config.xml and generated by 
                            file:/Users/takeda/projects/wilde/static/lib/staticSearch/xsl/create_config_xsl.xsl. See <xd:a href="create_config_xsl.xsl">create_config_xsl.xsl</xd:a>
                            (or https://github.com/projectEndings/staticSearch/blob/master/xsl/create_config_xsl.xsl)
                            for further information on how this document is created and the purpose it serves for the
                            staticSearch codebase.
                        </xd:p>
      </xd:desc>
   </xd:doc>
   <xsl:include href="/Users/takeda/projects/wilde/static/lib/staticSearch/stemmers/en//ssStemmer.xsl"/>
   <xsl:include href="constants.xsl"/>
   <xsl:param name="configFile">file:///Users/takeda/projects/wilde/static/staticSearch_config.xml</xsl:param>
   <xsl:param name="buildReportFilename" select="'staticSearch_report.html'"/>
   <xsl:param name="ssVerbose" select="'false'" as="xs:string" static="yes"/>
   <xsl:variable name="verbose" select="false()" as="xs:boolean" static="yes"/>
   <xsl:param name="output.dir" select="'search'"/>
   <xsl:param name="createContexts.maxKwicLength" select="15"/>
   <xsl:param name="index.recurse" select="false()"/>
   <xsl:param name="stopwords.file"
              select="'lib/staticSearch/stopwords/stopwords_en.txt'"/>
   <xsl:param name="createContexts.create" select="true()"/>
   <xsl:param name="results.maxResults" select="2000"/>
   <xsl:param name="createContexts.kwicTruncateString" select="'...'"/>
   <xsl:param name="tokenizer.minWordLength" select="3"/>
   <xsl:param name="results.resultsPerPage" select="50"/>
   <xsl:param name="createContexts.wildcardSearch" select="true()"/>
   <xsl:param name="stemmer.dir" select="'stemmers/en/'"/>
   <xsl:param name="createContexts.phrasalSearch" select="true()"/>
   <xsl:param name="version.file" select="'../public/COMMIT'"/>
   <xsl:param name="searchPage.file" select="'../public/search.html'"/>
   <xsl:param name="dictionary.file" select="'lib/staticSearch/dicts/words_en.txt'"/>
   <xsl:param name="createContexts.maxKwicsToHarvest" select="5"/>
   <xsl:param name="results.maxKwicsToShow" select="5"/>
   <xsl:param name="scoringAlgorithm.name" select="'tf-idf'"/>
   <xsl:param name="versionString">_e7415aa</xsl:param>
   <xsl:variable name="searchDocUri">file:/Users/takeda/projects/wilde/public/search.html</xsl:variable>
   <xsl:variable name="collectionDir">file:/Users/takeda/projects/wilde/public</xsl:variable>
   <xsl:variable name="outDir">file:/Users/takeda/projects/wilde/public/search</xsl:variable>
   <xsl:variable name="tempDir">file:/Users/takeda/projects/wilde/public/search/ssTemp</xsl:variable>
   <xsl:variable name="ssBaseDir">/Users/takeda/projects/wilde/static/lib/staticSearch</xsl:variable>
   <xsl:variable name="kwicLengthHalf" as="xs:integer" select="8"/>
   <xsl:variable name="collectionURI">file:/Users/takeda/projects/wilde/public?select=*.*htm*;recurse=no</xsl:variable>
   <xsl:variable name="docs"
                 select="collection($collectionURI)[not(starts-with(base-uri(.),$tempDir))]                                               [not(ends-with(base-uri(.), $buildReportFilename))]"/>
   <xsl:variable name="docUris"
                 select="uri-collection($collectionURI)[not(starts-with(.,$tempDir))]                                                   [not(ends-with(., $buildReportFilename))]"/>
   <xsl:variable name="tokenizedCollectionURI">file:/Users/takeda/projects/wilde/public/search/ssTemp?select=*_tokenized.*htm*;recurse=no</xsl:variable>
   <xsl:variable name="tokenizedDocs" select="collection($tokenizedCollectionURI)"/>
   <xsl:variable name="tokenizedUris" select="uri-collection($tokenizedCollectionURI)"/>
   <xsl:variable name="hasExclusions" select="true()"/>
   <xsl:variable name="hasFilterLabels" select="true()"/>
   <xsl:variable name="uri" select="xs:string(base-uri(.))" as="xs:string"/>
   <xd:doc>
      <xd:desc>The relative uri from the root:
                this is the full URI minus the collection dir. 
                Note that we TRIM off the leading slash</xd:desc>
   </xd:doc>
   <xsl:variable name="relativeUri"
                 select="substring-after($uri,replace($collectionDir, '^(file:/)/+', '$1')) =&gt; replace('^(/|\\)','')"
                 as="xs:string"/>
   <xsl:template name="echoParams">
      <xsl:if test="$verbose">
         <xsl:variable name="thisUri" select="static-base-uri()" as="xs:anyURI"/>
         <xsl:variable name="thisBasename"
                       select="tokenize($thisUri,'/')[last()]"
                       as="xs:string"/>
         <xsl:message>====== VARIABLES DECLARED IN <xsl:value-of select="static-base-uri()"/> =======</xsl:message>
         <xsl:for-each select="document(static-base-uri())//*:stylesheet/(*:param | *:variable)">
            <xsl:message>
               <xsl:value-of select="$thisBasename"/>: $<xsl:value-of select="@name"/>: <xsl:value-of select="@select"/> [<xsl:value-of select="local-name()"/>]</xsl:message>
         </xsl:for-each>
         <xsl:message>====== END PARAMETERS =======</xsl:message>
      </xsl:if>
   </xsl:template>
   <xsl:variable name="filterLabels" as="element(hcmc:filter)*">
      <filter xmlns="http://hcmc.uvic.ca/ns/staticSearch" filterName="dc.region.city">
         <span xmlns="http://www.w3.org/1999/xhtml" lang="en">City</span>
      </filter>
      <filter xmlns="http://hcmc.uvic.ca/ns/staticSearch" filterName="dc.date">
         <span xmlns="http://www.w3.org/1999/xhtml" lang="en">Date</span>
      </filter>
      <filter xmlns="http://hcmc.uvic.ca/ns/staticSearch" filterName="dc.region">
         <span xmlns="http://www.w3.org/1999/xhtml" lang="en">Region</span>
      </filter>
      <filter xmlns="http://hcmc.uvic.ca/ns/staticSearch" filterName="dc.language">
         <span xmlns="http://www.w3.org/1999/xhtml" lang="en">Language</span>
      </filter>
      <filter xmlns="http://hcmc.uvic.ca/ns/staticSearch" filterName="dc.publisher">
         <span xmlns="http://www.w3.org/1999/xhtml" lang="en">Publisher</span>
      </filter>
      <filter xmlns="http://hcmc.uvic.ca/ns/staticSearch" filterName="wr.word-count">
         <span xmlns="http://www.w3.org/1999/xhtml" lang="en">Word Count</span>
      </filter>
   </xsl:variable>
   <xsl:variable name="stopwordsFileXml"
                 select="doc('file:/Users/takeda/projects/wilde/public/search/dicts/stopwords_en.xml')"/>
   <xsl:key name="w" match="hcmc:word" use="."/>
   <xsl:template match="nav | *[contains-token(@class,'nav')] | div[contains-token(@class,'report-navigation')] | div[div[contains-token(@class,'page-header')]] |                 ul[@role='tablist'] | div[div[contains-token(@class,'panel')]] | footer"
                 priority="25"
                 mode="decorate">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:call-template name="hcmc:updateData">
         <xsl:with-param name="caller" select="'config#decorate'"/>
         <xsl:with-param name="key" select="$KEY_WEIGHTS"/>
         <xsl:with-param name="value" select="0"/>
         <xsl:with-param name="append">[rule/@match=nav | *[contains-token(@class,'nav')] | div[contains-token(@class,'report-navigation')] | div[div[contains-token(@class,'page-header')]] |                 ul[@role='tablist'] | div[div[contains-token(@class,'panel')]] | footer]</xsl:with-param>
      </xsl:call-template>
   </xsl:template>
   <xsl:template match="div[not(contains-token(@class,'matches-0'))][matches(@class,'matches-\d+')]"
                 priority="25"
                 mode="decorate">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:call-template name="hcmc:updateData">
         <xsl:with-param name="caller" select="'config#decorate'"/>
         <xsl:with-param name="key" select="$KEY_WEIGHTS"/>
         <xsl:with-param name="value" select="0"/>
         <xsl:with-param name="append">[rule/@match=div[not(contains-token(@class,'matches-0'))][matches(@class,'matches-\d+')]]</xsl:with-param>
      </xsl:call-template>
   </xsl:template>
   <xsl:template match="div[contains-token(@class,'col-sm-3')][a[contains-token(@class,'btn')][@title='Show matches']]"
                 priority="25"
                 mode="decorate">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:call-template name="hcmc:updateData">
         <xsl:with-param name="caller" select="'config#decorate'"/>
         <xsl:with-param name="key" select="$KEY_WEIGHTS"/>
         <xsl:with-param name="value" select="0"/>
         <xsl:with-param name="append">[rule/@match=div[contains-token(@class,'col-sm-3')][a[contains-token(@class,'btn')][@title='Show matches']]]</xsl:with-param>
      </xsl:call-template>
   </xsl:template>
   <xsl:template match="div[contains-token(@class,'similarity')]"
                 priority="25"
                 mode="decorate">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:call-template name="hcmc:updateData">
         <xsl:with-param name="caller" select="'config#decorate'"/>
         <xsl:with-param name="key" select="$KEY_WEIGHTS"/>
         <xsl:with-param name="value" select="0"/>
         <xsl:with-param name="append">[rule/@match=div[contains-token(@class,'similarity')]]</xsl:with-param>
      </xsl:call-template>
   </xsl:template>
   <xsl:template match="*[@lang][@lang ne 'en']" priority="25" mode="decorate">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:call-template name="hcmc:updateData">
         <xsl:with-param name="caller" select="'config#decorate'"/>
         <xsl:with-param name="key" select="$KEY_WEIGHTS"/>
         <xsl:with-param name="value" select="0"/>
         <xsl:with-param name="append">[rule/@match=*[@lang][@lang ne 'en']]</xsl:with-param>
      </xsl:call-template>
   </xsl:template>
   <xsl:template match="script | style" priority="25" mode="decorate">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:call-template name="hcmc:updateData">
         <xsl:with-param name="caller" select="'config#decorate'"/>
         <xsl:with-param name="key" select="$KEY_WEIGHTS"/>
         <xsl:with-param name="value" select="0"/>
         <xsl:with-param name="append">[rule/@match=script | style]</xsl:with-param>
      </xsl:call-template>
   </xsl:template>
   <xsl:variable name="ssContextMap" as="map(*)?">
      <xsl:sequence select="()"/>
   </xsl:variable>
   <xsl:template match="html[not(descendant::meta[@name='dc.date'])]"
                 priority="25"
                 mode="decorate">
      <xsl:call-template name="hcmc:updateData">
         <xsl:with-param name="caller" select="'config#decorate'"/>
         <xsl:with-param name="key" select="$KEY_EXCLUDES"/>
         <xsl:with-param name="value" select="true()"/>
         <xsl:with-param name="append">[exclude/@match=html[not(descendant::meta[@name='dc.date'])]]</xsl:with-param>
      </xsl:call-template>
   </xsl:template>
   <xsl:template match="*" name="hcmc:last" priority="1" mode="decorate">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:variable name="weights" select="$data($KEY_WEIGHTS)" as="xs:integer*"/>
      <xsl:variable name="ctxIds" select="$data($KEY_CONTEXT_IDS)" as="xs:string*"/>
      <xsl:variable name="contexts" select="$data($KEY_CONTEXTS)" as="xs:boolean*"/>
      <xsl:variable name="excludes" select="$data($KEY_EXCLUDES)" as="xs:boolean*"/>
      <xsl:choose>
         <xsl:when test="not(ancestor::*)">
            <xsl:if test="not(empty($weights)) and $weights[last()] = 0">
               <xsl:message terminate="yes">
                            *********************************************
                            ERROR: You have specified a weight of 0 for 
                            the root <xsl:value-of select="local-name()"/> element, 
                            which would create an empty output file and generate an error during 
                            tokenization.
                            
                            Did you mean to use an exclude instead?
                            *********************************************
                        </xsl:message>
            </xsl:if>
            <xsl:call-template name="hcmc:copy"/>
         </xsl:when>
         <xsl:when test="not(empty($weights))">
            <xsl:choose>
               <xsl:when test="$weights[last()] = 0">
                  <xsl:if test="$verbose">
                     <xsl:message>config#decorate: Removing <xsl:value-of select="local-name()"/> (weight=0)</xsl:message>
                  </xsl:if>
               </xsl:when>
               <xsl:otherwise>
                  <xsl:call-template name="hcmc:copy"/>
               </xsl:otherwise>
            </xsl:choose>
         </xsl:when>
         <xsl:when test="empty($contexts) or ($contexts[last()] = false())">
            <xsl:apply-templates select="node()" mode="#current"/>
         </xsl:when>
         <xsl:otherwise>
            <xsl:call-template name="hcmc:copy"/>
         </xsl:otherwise>
      </xsl:choose>
   </xsl:template>
   <xsl:template name="hcmc:updateData">
      <xsl:param name="data" tunnel="yes" as="map(*)"/>
      <xsl:param name="caller" as="xs:string?"/>
      <xsl:param name="append" as="xs:string?"/>
      <xsl:param name="key" as="xs:string"/>
      <xsl:param name="value" as="item()"/>
      <xsl:variable name="currValues" select="$data($key)" as="item()*"/>
      <xsl:variable name="newValues" select="($currValues, $value)" as="item()+"/>
      <xsl:if test="$verbose">
         <xsl:message>
            <xsl:value-of separator=": ">
               <xsl:text>hcmc:updateData</xsl:text>
               <xsl:sequence select="$caller"/>
               <xsl:sequence select="'Updating ' || local-name()"/>
               <xsl:sequence select="$key || '=' || string-join($newValues,';')"/>
            </xsl:value-of>
            <xsl:if test="not(empty($append))">
               <xsl:value-of select="' ' || $append"/>
            </xsl:if>
         </xsl:message>
      </xsl:if>
      <xsl:next-match>
         <xsl:with-param name="data"
                         tunnel="yes"
                         as="map(*)"
                         select="map:put($data, $key ,$newValues)"/>
      </xsl:next-match>
   </xsl:template>
   <xsl:template name="hcmc:copy">
      <xsl:copy>
         <xsl:call-template name="hcmc:copy-atts"/>
         <xsl:apply-templates select="node()" mode="decorate"/>
      </xsl:copy>
   </xsl:template>
   <xsl:template name="hcmc:copy-atts">
      <xsl:param name="data" as="map(*)" tunnel="yes"/>
      <xsl:if test="not(ancestor::*)">
         <xsl:attribute name="ss-uri" select="$relativeUri"/>
      </xsl:if>
      <xsl:apply-templates select="@*" mode="decorate"/>
      <xsl:where-populated>
         <xsl:attribute name="ss-wt" select="$data($KEY_WEIGHTS)[last()]"/>
      </xsl:where-populated>
      <xsl:where-populated>
         <xsl:attribute name="ss-ctx-id" select="string-join($data($KEY_CONTEXT_IDS), ' ')"/>
      </xsl:where-populated>
      <xsl:where-populated>
         <xsl:attribute name="ss-ctx" select="xs:string($data($KEY_CONTEXTS)[last()])"/>
      </xsl:where-populated>
      <xsl:where-populated>
         <xsl:attribute name="ss-excld" select="xs:string($data($KEY_EXCLUDES)[last()])"/>
      </xsl:where-populated>
   </xsl:template>
</xsl:stylesheet>
